### ISSUE TITLE
error messages with php 5.5+ and wikkawiki 1.3.6

### ISSUE THREAD

**Issue by vknews** [wikkawik/WikkaWiki#1199] opened 2015-07-03 11:27 UTC
Hi,
I get error messages "Warning: preg_replace(): Compilation failed: invalid range in character class at offset 16 in /webroot/s/t/strat023/lawilfo.com/www/libs/Wakka.class.php on line 2041" on pages where there are headers h1, h2... h5 (not called from actions. Only when I write them).

One error per header tag on the page.

**The reason seems to be WikkaWiki with php 5.5 or 5.6**
When I use php 5.4, no problem.

Example:
http://lawilfo.com/wikka.php?wakka=HomePage
(4 header tags: 4 error messages)

**Comment by tormodh** [comment] 2015-07-07 10:52
Hi,

This is a duplicate of issue #1181, and will be in version 1.3.7.

If you want to try, it is a small change in one line; see a82c0cd21824a1262f9f41247ab4e6e72c69f7df

**Closed by tormodh** 2015-07-07 10:52 UTC
Labels: duplicate
