### ISSUE TITLE
Table formatting error at end of page

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#1143] opened 2013-09-07 16:31 UTC
To reproduce: Create a table at the end of the page.  After the closing || do not enter any other characters or linefeeds.

The page rendering appears to get confused and will place the table contents after some of the final wiki formatting.  This is especially noticeable when doing a page preview.

The issue can be worked around by simply adding a space or linefeed after the closing pipes, however it can be quite frustrating to troubleshoot while previewing a new page.

**Comment by tormodh** [comment] 2015-04-28 21:23
Cannot reproduce. Please verify

**Comment by bakoontz** [comment] 2016-05-29 22:31
OP can't remember the initial conditions to reproduce, so I'm closing it.

**Closed by bakoontz** 2016-05-29 22:31 UTC
Labels: bug
